import type { AssociationCorpus } from "./engine.js";

export const associationCorpus: AssociationCorpus = {
  cards: [
    {
      id: "hackteria-diy-biology-projects",
      title: "Collection of DIY Biology, Open Source Art Projects",
      excerpt: "Hackteria collection including DIY biology, wetlab experiments, bacterial cellulose, bioplastics, Acetobacter xylinum, Kombucha SCOBY, Nata de Coco, and open source art projects.",
      keywords: ["hackteria", "bioart", "diy", "biology", "wetlab", "workshop", "kombucha", "bioplastic", "bacterial cellulose"],
      categories: ["Hackteria", "DIY biology", "open source art"],
      tags: ["hackteria", "biohack", "wetlab"],
      semanticTopics: [{ topic: "DIY biology and bioart materials", score: 0.93 }],
      sourceCategories: ["Hackteria"],
      source: "hackteria",
      url: "https://www.hackteria.org/wiki/Collection_of_DIY_Biology%2C_Open_Source_Art_Projects",
      path: "Sources/Raw/hackteria/collection-of-diy-biology-open-source-art-projects.md",
      outgoingLinks: ["hackteria-main-page", "sgmk-hacker-residence"],
    },
    {
      id: "hackteria-main-page",
      title: "Hackteria Main Page / Kitchenlab Bioplastic",
      excerpt: "Hackteria main page announces Kitchenlab Bioplastic workshop on biomaterials and bioplastic as novel material research, starting from the kitchen lab.",
      keywords: ["hackteria", "kitchenlab", "bioplastic", "biomaterial", "workshop", "food", "fermentation"],
      categories: ["Hackteria", "Kitchenlab"],
      tags: ["hackteria", "biomaterials"],
      semanticTopics: [{ topic: "kitchen lab biomaterials", score: 0.85 }],
      sourceCategories: ["Hackteria"],
      source: "hackteria",
      url: "https://www.hackteria.org/wiki/Main_Page",
      path: "Sources/Raw/hackteria/main-page.md",
      outgoingLinks: ["hackteria-diy-biology-projects", "sgmk-hacker-residence"],
    },
    {
      id: "sgmk-hacker-residence",
      title: "Hacker-in-Residence Programme",
      excerpt: "SGMK Hacker-in-Residence programme hosted Kitchenlab Bioplastic DIY workshop on biomaterials, bioplastic making, kitchen materials, reuse, repurpose, community lab experimentation, and tool-based workshops across art and technology.",
      keywords: ["sgmk", "hacker-in-residence", "bioplastic", "workshop", "community", "lab", "reuse", "materials", "tool", "experiment"],
      categories: ["SGMK", "residency", "workshop"],
      tags: ["sgmk", "hackteria", "bioplastic"],
      semanticTopics: [{ topic: "residency and community lab material workshops", score: 0.84 }],
      sourceCategories: ["SGMK"],
      source: "sgmk",
      url: "https://wiki.sgmk-ssam.ch/wiki/Hacker-in-Residence_Programme",
      path: "Sources/Raw/sgmk/hacker-in-residence-programme.md",
      outgoingLinks: ["hackteria-main-page", "hackteria-diy-biology-projects"],
    },
    {
      id: "sgmk-main-page",
      title: "SGMK Main Page",
      excerpt: "SGMK / Swiss Mechatronic Art Society documents workshops, festivals, mechatronic art, open hardware culture, sensors, circuits, instruments, and community infrastructure around experimental tools.",
      keywords: ["sgmk", "mechatronic", "art", "workshop", "festival", "community", "open hardware", "tools", "tool", "sensor", "circuit", "instrument"],
      categories: ["SGMK", "community infrastructure"],
      tags: ["sgmk", "mechatronic art"],
      semanticTopics: [{ topic: "mechatronic art community infrastructure", score: 0.82 }],
      sourceCategories: ["SGMK"],
      source: "sgmk",
      url: "https://wiki.sgmk-ssam.ch/wiki/Main_Page",
      path: "Sources/Raw/sgmk/main-page.md",
      outgoingLinks: ["sgmk-hacker-residence"],
    },
  ],
  edges: [
    { source: "hackteria-diy-biology-projects", target: "hackteria-main-page", relation: "bioart biomaterials", weight: 5 },
    { source: "hackteria-main-page", target: "sgmk-hacker-residence", relation: "Kitchenlab Bioplastic workshop bridge", weight: 5 },
    { source: "sgmk-hacker-residence", target: "sgmk-main-page", relation: "SGMK community infrastructure", weight: 4 },
  ],
  manifest: {
    schemaVersion: "pbs-association-minimal-public-corpus-v1",
    generatedAt: "manual:minimal-public-cards",
    counts: {
      sourceCards: 4,
      graphEdges: 3,
    },
  },
};
