import type { AssociationCorpus } from "./engine.js";

export const associationCorpus: AssociationCorpus = {
  cards: [
    {
      id: "htgwyw-fluffy-midi",
      title: "Fluffy MIDI wearable sound interface",
      excerpt: "KOBAKANT / How To Get What You Want workshop turning stuffed animals into MIDI interfaces with embroidery, needle felting, crochet, e-textile materials, capacitive sensing, and synthesizers.",
      keywords: ["wearable", "sound", "midi", "synthesizer", "e-textile", "sensor", "textile"],
      categories: ["How To Get What You Want / Kobakant", "workshop", "sound tools"],
      tags: ["htgwyw", "kobakant", "electronic textiles"],
      semanticTopics: [{ topic: "wearable sound interfaces", score: 0.92 }],
      sourceCategories: ["How To Get What You Want / Kobakant"],
      source: "htgwyw",
      url: "https://www.kobakant.at/DIY/?p=9948",
      path: "Sources/Raw/htgwyw/9948-fluffy-midi.md",
      outgoingLinks: ["htgwyw-playing-electronic-textiles", "htgwyw-woolly-noise"],
    },
    {
      id: "htgwyw-playing-electronic-textiles",
      title: "Playing with electronic textiles",
      excerpt: "Workshop introducing materials, design, and didactic possibilities of electronic textiles. Participants develop object-, body-, and space-oriented projects with textile sensors, circuits, sound, and cardboard synth examples.",
      keywords: ["electronic", "textiles", "sensor", "circuit", "sound", "workshop", "pedagogy"],
      categories: ["How To Get What You Want / Kobakant", "workshop"],
      tags: ["htgwyw", "kobakant", "material design"],
      semanticTopics: [{ topic: "textile sensors and sound pedagogy", score: 0.9 }],
      sourceCategories: ["How To Get What You Want / Kobakant"],
      source: "htgwyw",
      url: "https://www.kobakant.at/DIY/?p=9812",
      path: "Sources/Raw/htgwyw/9812-playing-with-electronic-textiles.md",
      outgoingLinks: ["htgwyw-fluffy-midi", "htgwyw-woolly-noise"],
    },
    {
      id: "htgwyw-woolly-noise",
      title: "Stitching Electronics | Woolly Noise",
      excerpt: "Textile sensors made with silver conductive thread and resistive textile materials change resistance through pressure, stretch, and bend, enabling handmade music interfaces and sound experiments.",
      keywords: ["textile", "sensor", "conductive", "resistance", "pressure", "bend", "music", "interface"],
      categories: ["How To Get What You Want / Kobakant", "materials"],
      tags: ["htgwyw", "kobakant", "soft circuits"],
      semanticTopics: [{ topic: "soft circuit music interfaces", score: 0.88 }],
      sourceCategories: ["How To Get What You Want / Kobakant"],
      source: "htgwyw",
      url: "https://www.kobakant.at/DIY/?p=9540",
      path: "Sources/Raw/htgwyw/9540-stitching-electronics-woolly-noise.md",
      outgoingLinks: ["htgwyw-fluffy-midi", "htgwyw-tone-of-things"],
    },
    {
      id: "htgwyw-tone-of-things",
      title: "Tone of the Things",
      excerpt: "Collection of pressure sensors, felt squeeze sensors, stretch sensors, textile voltage-divider circuits, and Arduino examples for making objects sound and respond.",
      keywords: ["sensor", "pressure", "stretch", "arduino", "textile", "sound", "circuit"],
      categories: ["How To Get What You Want / Kobakant", "tutorial"],
      tags: ["htgwyw", "kobakant", "sensors"],
      semanticTopics: [{ topic: "sensor circuits for sound objects", score: 0.86 }],
      sourceCategories: ["How To Get What You Want / Kobakant"],
      source: "htgwyw",
      url: "https://www.kobakant.at/DIY/?p=9649",
      path: "Sources/Raw/htgwyw/9649-tone-of-the-things.md",
      outgoingLinks: ["htgwyw-woolly-noise"],
    },
    {
      id: "hackteria-diy-biology-projects",
      title: "Collection of DIY Biology, Open Source Art Projects",
      excerpt: "Hackteria collection including DIY biology, wetlab experiments, bacterial cellulose, bioplastics, Acetobacter xylinum, Kombucha SCOBY, Nata de Coco, and open source art projects.",
      keywords: ["hackteria", "bioart", "diy", "biology", "wetlab", "workshop", "kombucha", "bioplastic", "bacterial cellulose"],
      categories: ["Hackteria", "DIY biology", "open source art"],
      tags: ["hackteria", "biohack", "wetlab"],
      semanticTopics: [{ topic: "DIY biology and bioart materials", score: 0.93 }],
      sourceCategories: ["Hackteria"],
      source: "hackteria",
      url: "https://www.hackteria.org/wiki/Collection_of_DIY_Biology%2C_Open_Source_Art_Projects",
      path: "Sources/Raw/hackteria/collection-of-diy-biology-open-source-art-projects.md",
      outgoingLinks: ["hackteria-main-page", "sgmk-hacker-residence"],
    },
    {
      id: "hackteria-main-page",
      title: "Hackteria Main Page / Kitchenlab Bioplastic",
      excerpt: "Hackteria main page announces Kitchenlab Bioplastic workshop on biomaterials and bioplastic as novel material research, starting from the kitchen lab.",
      keywords: ["hackteria", "kitchenlab", "bioplastic", "biomaterial", "workshop", "food", "fermentation"],
      categories: ["Hackteria", "Kitchenlab"],
      tags: ["hackteria", "biomaterials"],
      semanticTopics: [{ topic: "kitchen lab biomaterials", score: 0.85 }],
      sourceCategories: ["Hackteria"],
      source: "hackteria",
      url: "https://www.hackteria.org/wiki/Main_Page",
      path: "Sources/Raw/hackteria/main-page.md",
      outgoingLinks: ["hackteria-diy-biology-projects", "sgmk-hacker-residence"],
    },
    {
      id: "sgmk-hacker-residence",
      title: "Hacker-in-Residence Programme",
      excerpt: "SGMK Hacker-in-Residence programme hosted Kitchenlab Bioplastic DIY workshop on biomaterials, bioplastic making, kitchen materials, reuse, repurpose, community lab experimentation, and tool-based workshops across art and technology.",
      keywords: ["sgmk", "hacker-in-residence", "bioplastic", "workshop", "community", "lab", "reuse", "materials", "tool", "experiment"],
      categories: ["SGMK", "residency", "workshop"],
      tags: ["sgmk", "hackteria", "bioplastic"],
      semanticTopics: [{ topic: "residency and community lab material workshops", score: 0.84 }],
      sourceCategories: ["SGMK"],
      source: "sgmk",
      url: "https://wiki.sgmk-ssam.ch/wiki/Hacker-in-Residence_Programme",
      path: "Sources/Raw/sgmk/hacker-in-residence-programme.md",
      outgoingLinks: ["hackteria-main-page", "hackteria-diy-biology-projects"],
    },
    {
      id: "sgmk-main-page",
      title: "SGMK Main Page",
      excerpt: "SGMK / Swiss Mechatronic Art Society documents workshops, festivals, mechatronic art, open hardware culture, sensors, circuits, instruments, and community infrastructure around experimental tools.",
      keywords: ["sgmk", "mechatronic", "art", "workshop", "festival", "community", "open hardware", "tools", "tool", "sensor", "circuit", "instrument"],
      categories: ["SGMK", "community infrastructure"],
      tags: ["sgmk", "mechatronic art"],
      semanticTopics: [{ topic: "mechatronic art community infrastructure", score: 0.82 }],
      sourceCategories: ["SGMK"],
      source: "sgmk",
      url: "https://wiki.sgmk-ssam.ch/wiki/Main_Page",
      path: "Sources/Raw/sgmk/main-page.md",
      outgoingLinks: ["sgmk-hacker-residence"],
    },
  ],
  edges: [
    { source: "htgwyw-fluffy-midi", target: "htgwyw-playing-electronic-textiles", relation: "shared e-textile sound workshop", weight: 5 },
    { source: "htgwyw-playing-electronic-textiles", target: "htgwyw-woolly-noise", relation: "textile sensor pedagogy", weight: 5 },
    { source: "htgwyw-woolly-noise", target: "htgwyw-tone-of-things", relation: "sensor circuit material practice", weight: 4 },
    { source: "hackteria-diy-biology-projects", target: "hackteria-main-page", relation: "bioart biomaterials", weight: 5 },
    { source: "hackteria-main-page", target: "sgmk-hacker-residence", relation: "Kitchenlab Bioplastic workshop bridge", weight: 5 },
    { source: "sgmk-hacker-residence", target: "sgmk-main-page", relation: "SGMK community infrastructure", weight: 4 },
    { source: "htgwyw-playing-electronic-textiles", target: "sgmk-main-page", relation: "workshop infrastructure bridge", weight: 3 },
  ],
  manifest: {
    schemaVersion: "pbs-association-minimal-public-corpus-v1",
    generatedAt: "manual:minimal-public-cards",
    counts: {
      sourceCards: 8,
      graphEdges: 7,
    },
  },
};
