import type zhTW from "./zh-TW.js";
const en: typeof zhTW = {
    common: { close: "Close", confirm: "Confirm", cancel: "Cancel", loading: "Loading...", generate: "Generate", language: "Language", open: "Open", save: "Save" },
    language: { menuLabel: "Language", selectLanguage: "Select language", currentLanguage: "Current language: {name}" },
    home: { ngmLabel: "Non-Governmental Matters", title: "桃花源：可思考的生命模擬器派遣", subtitle: "An interactive fable dimension for Non-Governmental Matters", description: "這是一個互動寓言維度，許多奇怪的朋友在這裡一起做著奇怪的實驗和音樂，一起煮飯生活著，你無意間闖入這個世界並試圖探索並收集如何建造一個烏托邦的方法和試著記住回到這裡的路...\n\n這個遊戲的本體是一個研究訪談稿\"Non-Governmental Matters\"，該研究採訪了14位獨立科技藝術組織者和藝術家，關於經營社群可持續性的看法。這些受訪者的看法被轉化成遊戲裡可以以自然語言進行交談的NPC，背後的大語言模型目前是經訪談逐字稿調校過後的Deepseek flash。你還可以用一個問題創造出一隻電子雞，這個電子雞會隨著與遊戲世界的互動而成長，最後得到一個經由社群集體智能處理過後的解決方案與回應。在遊戲的中央放置了研究案的文本、社群最新消息和社群地圖，歡迎隨便到處逛逛！", createProtagonist: "Create protagonist", createTraveler: "Create otherworld traveler", playerNameLabel: "Name", playerNamePlaceholder: "Enter your character name", roleLabel: "Current role", rolePlaceholder: "Independent researcher, artist, engineer, village summoner...", missionLabel: "What do I want?", missionPlaceholder: "Describe the wish, need, or future you want this avatar to bring into Peach Blossom Spring.", constraintsLabel: "Constraints (optional)", constraintsPlaceholder: "No corporate dashboard, tiny budget, must be open source, prototype in three months...", avatarCollection: "Place character", skillsLabel: "What skills do I have?", skillsPlaceholder: "Field research, open hardware, curation, community organizing, textiles, coding.", enterWorld: "Enter Peach Blossom Spring", startButton: "Generate / Start", sendOnExpedition: "Send Mr. WHY", movementHint: "Move with arrow keys or WASD. On mobile, drag the thumb circle at bottom left. Hold Shift to speed up.", wanderAndTalk: "Wander & Talk", rotateHint: "Rotate (R)" },
    setup: { kicker: "NGM / Peach gate console", title: "Question Pet Boot Screen", nameLabel: "Name", namePlaceholder: "What should Peach Blossom Spring call you?", questionLabel: "Enter one question you want to explore", questionPlaceholder: "Example: how do we build a utopia that does not turn people into dashboards?", skillsLabel: "What skills do I have?", skillsPlaceholder: "Fieldwork, cooking, coding, listening, sewing, summoning friends...", booting: "Question pet hatched — pausing 3 seconds to admire it...", blank: "Waiting for all three fields", born: "Beep! It was born. It already looks ready to run away.", keeper: "Question Pet Keeper", petControls: "Pet controls", choosePet: "Choose pet", fixedPetMenu: "Fixed pet menu" },
    dialogue: { title: "Dialogue", askQuestion: "Ask me a question", askNpc: "Ask {name} a question", inputPlaceholder: "{name} - What would you like to ask?", talkButton: "Talk", closeButton: "Close", openWiki: "Open Wiki", openExternalPage: "Open external page", thinking: "is thinking...", teachMe: "What can you teach me?", whereIsThis: "Where am I?", fallbackMission: "the mission I am working on", fallbackSkills: "my skills", requestFailed: "DeepSeek proxy request failed." },
    archive: { tree: "Archive tree", title: "Central tree", description: "Open news, the e-book, and the community map from here.", newsTitle: "Latest news", ebookButton: "NGM e-book", mapButton: "The Map", pdfTitle: "NGM PDF embedded e-book", mapTitle: "NGM community map", communityPortals: "Community portals", embeddedLink: "Embedded link", worldWiki: "World Wiki", noWikiLinks: "No wiki links yet" },
    hud: { zoomIn: "Zoom in", zoomOut: "Zoom out", openChat: "Open chat", openExternal: "Open external link", language: "Language", pressToTalk: "Tap to talk", loadingExpedition: "Loading expedition...", questionPetSim: "Question Pet SIM", tick: "Tick" },
    pet: { questionPet: "Question Pet", keeper: "Question Pet Keeper", generating: "Generating...", generationFailed: "Generation failed", traits: "Traits", energy: "Energy", stress: "Stress", bond: "Bond", skill: "Skill", originalQuestionPurpose: "Original question / purpose", responses: "Responses", shareIdeaPlaceholder: "Share an idea, clue, or response…", postResponse: "Post response", noResponsesYet: "No responses yet", returnedNotes: "Your pet returned with {count} field notes.", localOnlyNotice: "This version stores dispatch records locally. Cross-user sync requires a future server backend.", smallCircleEvent: "A small circle of question-pets begins exchanging failed attempts.", hibernationEvent: "Some question-pets slip into the grass to hibernate, waiting to be recalled.", worldResonanceEvent: "Peach Blossom Spring briefly becomes a network that answers itself.", status: "Status", active: "Active", hibernating: "Hibernating", archived: "Archived", fieldNotes: "Field notes", sendFieldNote: "Send field note", fieldNotePlaceholder: "Write a short field note...", dispatchPetOnly: "Dispatch pet only", dispatchArchive: "Dispatch archive", localDispatchRecords: "Local dispatch records" },
    expedition: { title: "Peach Blossom Spring: Dispatching a Thinking Life Simulator", templateSimulation: "Template simulation", description: "Dispatch your mission into Peach Blossom Spring and let NPCs collide through memory, extrapolation, and speculation.", playerSummary: "Expedition avatar", constraints: "Constraints", skills: "Skills", noConstraints: "none declared", mission: "Mission", maxRounds: "Max rounds", selectedNpcs: "Selected NPCs", run: "Send Mr. WHY", running: "Mr. WHY is away...", liveLog: "Live event log", noEvents: "No expedition events yet.", round: "Round", challenge: "Challenge", lead: "Lead", nextQuestion: "Next question", report: "Expedition Report", reportTitle: "Peach Blossom Spring Mr. WHY Report", originalMission: "Original mission", interpretedMission: "Interpreted mission", emergentDirection: "Emergent direction", keyEncounters: "Key Encounters", npcDisagreements: "NPC Disagreements", blindSpots: "Blind Spots", nextActions: "Concrete Next Actions", followUpQuestions: "Follow-Up Questions", researchLeads: "Open-Call / Research Leads", downloadReport: "Download .md report", reportFilename: "peach-blossom-mr-why-report.md" },
    encounter: { frictionCircle: "Friction circle", fieldTest: "Field test", nightKitchenArgument: "Night kitchen argument", archiveDetour: "Archive detour", prototypeOmen: "Prototype omen", abaoTitle: "Abao encounter", abaoHint: "Move near Abao and see how rhythm changes the question.", hatchEnter: "Hatch and enter" },
    api: { keyMissing: "API key missing", keyMissingInstruction: "Set VITE_DEEPSEEK_API_KEY in webview-ui/.env.local, or save it once in local browser storage.", localSettings: "Local API key settings", keyLabel: "DeepSeek API key", saveLocally: "Save locally", savedLocally: "Saved locally", clearSavedKey: "Clear saved key" },
    sim: { observerMode: "Observer mode without character", stats: "Stats", npcLabel: "NPC" },
    errors: { generic: "Something went wrong.", emptyQuestion: "Please enter a question first.", generationFailed: "Generation failed. Please try again." },
};
export default en;
