import type zhTW from "./zh-TW.js";
const en: typeof zhTW = {
    common: { close: "Close", confirm: "Confirm", cancel: "Cancel", loading: "Loading...", generate: "Generate", language: "Language", open: "Open", save: "Save" },
    language: { menuLabel: "Language", selectLanguage: "Select language", currentLanguage: "Current language: {name}" },
    home: { ngmLabel: "Non-Governmental Matters", title: "Peach Blossom Spring: Dispatching a Thinking Life Simulator", subtitle: "An interactive fable dimension for Non-Governmental Matters", description: "This is an interactive fable dimension where strange friends make music and odd experiments together. You found a path here by accident, and now you can explore and collect ways to build a utopia. Talk freely with the friends who live here; every opinion hides treasure. Remember that everything you do affects this free world, and you may discover how dreams couple with reality.", createProtagonist: "Create protagonist", createTraveler: "Create otherworld traveler", playerNameLabel: "Name", playerNamePlaceholder: "Enter your character name", roleLabel: "Current role", rolePlaceholder: "Independent researcher, artist, engineer, village summoner...", missionLabel: "What do I want?", missionPlaceholder: "Describe the wish, need, or future you want this avatar to bring into Peach Blossom Spring.", constraintsLabel: "Constraints (optional)", constraintsPlaceholder: "No corporate dashboard, tiny budget, must be open source, prototype in three months...", avatarCollection: "Place character", skillsLabel: "What skills do I have?", skillsPlaceholder: "Field research, open hardware, curation, community organizing, textiles, coding.", enterWorld: "Enter Peach Blossom Spring", startButton: "Generate / Start", sendOnExpedition: "Send Mr. WHY", movementHint: "Move with arrow keys or WASD. On mobile, drag the thumb circle at bottom left. Hold Shift to speed up.", wanderAndTalk: "Wander & Talk", rotateHint: "Rotate (R)" },
    setup: { kicker: "NGM / Peach gate console", title: "Question Pet Boot Screen", nameLabel: "Name", namePlaceholder: "What should Peach Blossom Spring call you?", questionLabel: "Enter one question you want to explore", questionPlaceholder: "Example: how do we build a utopia that does not turn people into dashboards?", skillsLabel: "What skills do I have?", skillsPlaceholder: "Fieldwork, cooking, coding, listening, sewing, summoning friends...", booting: "Question pet hatched — pausing 3 seconds to admire it...", blank: "Waiting for all three fields", born: "Beep! It was born. It already looks ready to run away.", keeper: "Question Pet Keeper", petControls: "Pet controls" },
    dialogue: { title: "Dialogue", askQuestion: "Ask me a question", askNpc: "Ask {name} a question", inputPlaceholder: "{name} - What would you like to ask?", talkButton: "Talk", closeButton: "Close", openWiki: "Open Wiki", openExternalPage: "Open external page", thinking: "is thinking...", teachMe: "What can you teach me?", whereIsThis: "Where am I?", fallbackMission: "the mission I am working on", fallbackSkills: "my skills", requestFailed: "DeepSeek proxy request failed." },
    archive: { tree: "Archive tree", title: "Central tree", description: "Open news, the e-book, and the community map from here.", newsTitle: "Latest news", ebookButton: "NGM e-book", mapButton: "The Map", pdfTitle: "NGM PDF embedded e-book", mapTitle: "NGM community map", communityPortals: "Community portals", embeddedLink: "Embedded link", worldWiki: "World Wiki", noWikiLinks: "No wiki links yet" },
    hud: { zoomIn: "Zoom in", zoomOut: "Zoom out", openChat: "Open chat", openExternal: "Open external link", language: "Language", pressToTalk: "Tap to talk", loadingExpedition: "Loading expedition...", questionPetSim: "Question Pet SIM", tick: "Tick" },
    pet: { questionPet: "Question Pet", keeper: "Question Pet Keeper", generating: "Generating...", generationFailed: "Generation failed", traits: "Traits", energy: "Energy", stress: "Stress", bond: "Bond", skill: "Skill", originalQuestionPurpose: "Original question / purpose", responses: "Responses", shareIdeaPlaceholder: "Share an idea, clue, or response…", postResponse: "Post response", noResponsesYet: "No responses yet", returnedNotes: "Your pet returned with {count} field notes.", localOnlyNotice: "This version stores dispatch records locally. Cross-user sync requires a future server backend.", smallCircleEvent: "A small circle of question-pets begins exchanging failed attempts.", hibernationEvent: "Some question-pets slip into the grass to hibernate, waiting to be recalled.", worldResonanceEvent: "Peach Blossom Spring briefly becomes a network that answers itself.", status: "Status", active: "Active", hibernating: "Hibernating", archived: "Archived", fieldNotes: "Field notes", sendFieldNote: "Send field note", fieldNotePlaceholder: "Write a short field note...", dispatchPetOnly: "Dispatch pet only", dispatchArchive: "Dispatch archive", localDispatchRecords: "Local dispatch records" },
    expedition: { title: "Peach Blossom Spring: Dispatching a Thinking Life Simulator", templateSimulation: "Template simulation", description: "Dispatch your mission into Peach Blossom Spring and let NPCs collide through memory, extrapolation, and speculation.", playerSummary: "Expedition avatar", constraints: "Constraints", skills: "Skills", noConstraints: "none declared", mission: "Mission", maxRounds: "Max rounds", selectedNpcs: "Selected NPCs", run: "Send Mr. WHY", running: "Mr. WHY is away...", liveLog: "Live event log", noEvents: "No expedition events yet.", round: "Round", challenge: "Challenge", lead: "Lead", nextQuestion: "Next question", report: "Expedition Report", reportTitle: "Peach Blossom Spring Mr. WHY Report", originalMission: "Original mission", interpretedMission: "Interpreted mission", emergentDirection: "Emergent direction", keyEncounters: "Key Encounters", npcDisagreements: "NPC Disagreements", blindSpots: "Blind Spots", nextActions: "Concrete Next Actions", followUpQuestions: "Follow-Up Questions", researchLeads: "Open-Call / Research Leads", downloadReport: "Download .md report", reportFilename: "peach-blossom-mr-why-report.md" },
    encounter: { frictionCircle: "Friction circle", fieldTest: "Field test", nightKitchenArgument: "Night kitchen argument", archiveDetour: "Archive detour", prototypeOmen: "Prototype omen", abaoTitle: "Abao encounter", abaoHint: "Move near Abao and see how rhythm changes the question.", hatchEnter: "Hatch and enter" },
    api: { keyMissing: "API key missing", keyMissingInstruction: "Set VITE_DEEPSEEK_API_KEY in webview-ui/.env.local, or save it once in local browser storage.", localSettings: "Local API key settings", keyLabel: "DeepSeek API key", saveLocally: "Save locally", savedLocally: "Saved locally", clearSavedKey: "Clear saved key" },
    sim: { observerMode: "Observer mode without character", stats: "Stats", npcLabel: "NPC" },
    errors: { generic: "Something went wrong.", emptyQuestion: "Please enter a question first.", generationFailed: "Generation failed. Please try again." },
};
export default en;

