import type zhTW from "./zh-TW.js";
const ja: typeof zhTW = {
    common: { close: "閉じる", confirm: "決定", cancel: "キャンセル", loading: "読み込み中...", generate: "生成", language: "言語", open: "開く", save: "保存" },
    language: { menuLabel: "言語", selectLanguage: "言語を選択", currentLanguage: "現在の言語：{name}" },
    home: { ngmLabel: "Non-Governmental Matters", title: "桃花源：思考する生命シミュレーターを派遣", subtitle: "Non-Governmental Matters のインタラクティブな寓話世界", description: "ここはインタラクティブな寓話の次元です。たくさんの不思議な友人たちが、奇妙な実験や音楽をしたり、料理をしたりしながら一緒に暮らしています。あなたは偶然この世界に迷い込み、ユートピアを建てる方法を探して集めながら、ここへ戻ってくる道を覚えようとしています...\n\nこのゲームの本体は、研究インタビュー記録「Non-Governmental Matters」です。この研究では、独立したテクノロジー・アートのオーガナイザーやアーティスト14名に、コミュニティ運営の持続可能性についての考えを聞きました。回答者たちの視点は、ゲーム内で自然言語によって会話できるNPCへと変換されています。その背後にある大規模言語モデルは、現在、インタビュー逐語録で調整されたDeepseek flashです。また、ひとつの問いから質問ペットを作ることもできます。この電子ペットはゲーム世界との相互作用を通じて成長し、最後にはコミュニティの集合知によって処理された解決策と応答を受け取ります。ゲームの中央には、研究プロジェクトのテキスト、コミュニティの最新情報、コミュニティ地図が置かれています。どうぞ自由に歩き回ってください！", createProtagonist: "主人公を作成", createTraveler: "異世界の旅人を作成", playerNameLabel: "名前", playerNamePlaceholder: "キャラクター名を入力", roleLabel: "現在の役割", rolePlaceholder: "例：独立研究者、アーティスト、エンジニア、村の召喚師", missionLabel: "自分は何を望んでいる？", missionPlaceholder: "このアバターが桃花源に持ち込みたい願い、必要なもの、共に育てたい未来を書いてください。", constraintsLabel: "制約（任意）", constraintsPlaceholder: "例：企業向けダッシュボードにしない、予算が小さい、オープンソース必須、3か月で試作。", avatarCollection: "キャラクターを配置", skillsLabel: "自分にはどんな技能がある？", skillsPlaceholder: "例：フィールド調査、オープンハードウェア、キュレーション、コミュニティ運営、布、プログラミング。", enterWorld: "桃花源に入る", startButton: "生成 / 開始", sendOnExpedition: "Mr. WHY を派遣", movementHint: "矢印キーまたは WASD で移動。スマホでは左下の親指サークルをドラッグ。Shift 長押しで加速。", wanderAndTalk: "散策と会話", rotateHint: "回転（R）" },
    setup: { kicker: "NGM / 桃花源入口端末", title: "質問ペット起動画面", nameLabel: "名前", namePlaceholder: "桃花源では何と呼ばれたい？", questionLabel: "探索したい問いをひとつ入力", questionPlaceholder: "例：人をダッシュボードにしないユートピアをどう作る？", skillsLabel: "自分にはどんな技能がある？", skillsPlaceholder: "フィールドワーク、料理、コード、聞くこと、縫製、友だち召喚...", booting: "質問ペットが生まれました。3秒眺めてから入ります...", blank: "三つの欄の入力待ち", born: "ピッ！生まれた。もう逃げ出す顔をしている。", keeper: "質問ペットの飼い主", petControls: "ペット操作", choosePet: "ペットを選択", fixedPetMenu: "固定ペットメニュー" },
    dialogue: { title: "対話", askQuestion: "質問してみる", askNpc: "{name} に質問する", inputPlaceholder: "{name} - 何を聞きたい？", talkButton: "話す", closeButton: "閉じる", openWiki: "Wiki を開く", openExternalPage: "外部ページを開く", thinking: "考え中...", teachMe: "何を教えてくれる？", whereIsThis: "ここはどこ？", fallbackMission: "いま考えている任務", fallbackSkills: "自分の技能", requestFailed: "DeepSeek プロキシへのリクエストに失敗しました。" },
    archive: { tree: "アーカイブの木", title: "中央の木", description: "ここから最新情報、電子書籍、コミュニティ地図を開けます。", newsTitle: "最新情報", ebookButton: "NGM e-book", mapButton: "The Map", pdfTitle: "NGM PDF 埋め込み電子書籍", mapTitle: "NGM コミュニティ地図", communityPortals: "コミュニティ入口", embeddedLink: "埋め込みリンク", worldWiki: "World Wiki", noWikiLinks: "Wiki リンクはまだありません" },
    hud: { zoomIn: "拡大", zoomOut: "縮小", openChat: "対話を開く", openExternal: "外部リンクを開く", language: "言語", pressToTalk: "タップして話す", loadingExpedition: "派遣パネルを読み込み中...", questionPetSim: "質問ペット SIM", tick: "ティック" },
    pet: { questionPet: "質問ペット", keeper: "質問ペットの飼い主", generating: "生成中...", generationFailed: "生成に失敗しました", traits: "特徴", energy: "エネルギー", stress: "ストレス", bond: "絆", skill: "技能", originalQuestionPurpose: "元の問い / 目的", responses: "応答", shareIdeaPlaceholder: "アイデア、手がかり、応答を共有…", postResponse: "応答を送る", noResponsesYet: "まだ応答はありません", returnedNotes: "ペットが {count} 件のフィールドノートを持ち帰りました。", localOnlyNotice: "この版では派遣記録をローカルに保存します。ユーザー間同期には今後のサーバーが必要です。", smallCircleEvent: "小さな質問ペットの輪が、失敗した試みを交換し始めました。", hibernationEvent: "いくつかの質問ペットは草むらで休眠し、呼び戻されるのを待っています。", worldResonanceEvent: "桃花源が一瞬、互いに応答するネットワークになりました。", status: "状態", active: "活動中", hibernating: "休眠中", archived: "アーカイブ済み", fieldNotes: "フィールドノート", sendFieldNote: "フィールドノートを送る", fieldNotePlaceholder: "短いフィールドノートを書く...", dispatchPetOnly: "ペットだけ派遣", dispatchArchive: "派遣アーカイブ", localDispatchRecords: "ローカル派遣記録" },
    expedition: { title: "桃花源：考える生命シミュレーター派遣", templateSimulation: "テンプレート・シミュレーション", description: "あなたの任務を桃花源へ派遣し、NPC たちを記憶、推論、想像で衝突させます。", playerSummary: "派遣アバター", constraints: "制約", skills: "技能", noConstraints: "未指定", mission: "任務", maxRounds: "最大ラウンド", selectedNpcs: "選択中の NPC", run: "Mr. WHY を送る", running: "Mr. WHY が外出中...", liveLog: "ライブイベント記録", noEvents: "派遣イベントはまだありません。", round: "ラウンド", challenge: "課題", lead: "手がかり", nextQuestion: "次の問い", report: "派遣レポート", reportTitle: "桃花源 Mr. WHY 派遣レポート", originalMission: "元の任務", interpretedMission: "解釈された任務", emergentDirection: "生まれた方向性", keyEncounters: "重要な遭遇", npcDisagreements: "NPC の意見差", blindSpots: "盲点", nextActions: "具体的な次の行動", followUpQuestions: "追加の問い", researchLeads: "公募 / 研究の手がかり", downloadReport: ".md レポートをダウンロード", reportFilename: "peach-blossom-mr-why-report-ja.md" },
    encounter: { frictionCircle: "摩擦の輪", fieldTest: "フィールドテスト", nightKitchenArgument: "夜の台所での議論", archiveDetour: "アーカイブへの寄り道", prototypeOmen: "プロトタイプの兆し", abaoTitle: "Abao との遭遇", abaoHint: "Abao に近づき、リズムが問いをどう変えるか見てください。", hatchEnter: "孵化して入る" },
    abao: { lines: "WTF|haha|どうしよう！|なぜぇぇぇぇ！！|退屈だなあ…|意識を研究するのが好き|Wise Mouse Culture！|エネルギーとアイデンティティって何だろう？|AI agent に夢は必要？|今日は太陽が出ている？|ハッカーキャンプに行きたい" },
    api: { keyMissing: "API key がありません", keyMissingInstruction: "webview-ui/.env.local に VITE_DEEPSEEK_API_KEY を設定するか、ローカルブラウザ保存を一度行ってください。", localSettings: "ローカル API key 設定", keyLabel: "DeepSeek API key", saveLocally: "ローカルに保存", savedLocally: "ローカル保存済み", clearSavedKey: "保存済み key を削除" },
    sim: { observerMode: "キャラクターなし観察モード", stats: "統計", npcLabel: "NPC" },
    errors: { generic: "エラーが発生しました。", emptyQuestion: "先に質問を入力してください。", generationFailed: "生成に失敗しました。もう一度お試しください。" },
};
export default ja;
