import type zhTW from "./zh-TW.js";
const ja: typeof zhTW = {
    common: { close: "閉じる", confirm: "決定", cancel: "キャンセル", loading: "読み込み中...", generate: "生成", language: "言語", open: "開く", save: "保存" },
    language: { menuLabel: "言語", selectLanguage: "言語を選択", currentLanguage: "現在の言語：{name}" },
    home: { ngmLabel: "Non-Governmental Matters", title: "桃花源：可思考的生命模擬器派遣", subtitle: "Non-Governmental Matters のインタラクティブな寓話世界", description: "這是一個互動寓言維度，許多奇怪的朋友在這裡一起做著奇怪的實驗和音樂，一起煮飯生活著，你無意間闖入這個世界並試圖探索並收集如何建造一個烏托邦的方法和試著記住回到這裡的路...\n\n這個遊戲的本體是一個研究訪談稿\"Non-Governmental Matters\"，該研究採訪了14位獨立科技藝術組織者和藝術家，關於經營社群可持續性的看法。這些受訪者的看法被轉化成遊戲裡可以以自然語言進行交談的NPC，背後的大語言模型目前是經訪談逐字稿調校過後的Deepseek flash。你還可以用一個問題創造出一隻電子雞，這個電子雞會隨著與遊戲世界的互動而成長，最後得到一個經由社群集體智能處理過後的解決方案與回應。在遊戲的中央放置了研究案的文本、社群最新消息和社群地圖，歡迎隨便到處逛逛！", createProtagonist: "主人公を作成", createTraveler: "異世界の旅人を作成", playerNameLabel: "名前", playerNamePlaceholder: "キャラクター名を入力", roleLabel: "現在の役割", rolePlaceholder: "例：独立研究者、アーティスト、エンジニア、村の召喚師", missionLabel: "自分は何を望んでいる？", missionPlaceholder: "このアバターが桃花源に持ち込みたい願い、必要なもの、共に育てたい未来を書いてください。", constraintsLabel: "制約（任意）", constraintsPlaceholder: "例：企業向けダッシュボードにしない、予算が小さい、オープンソース必須、3か月で試作。", avatarCollection: "キャラクターを配置", skillsLabel: "自分にはどんな技能がある？", skillsPlaceholder: "例：フィールド調査、オープンハードウェア、キュレーション、コミュニティ運営、布、プログラミング。", enterWorld: "桃花源に入る", startButton: "生成 / 開始", sendOnExpedition: "Mr. WHY を派遣", movementHint: "矢印キーまたは WASD で移動。スマホでは左下の親指サークルをドラッグ。Shift 長押しで加速。", wanderAndTalk: "散策と会話", rotateHint: "回転（R）" },
    setup: { kicker: "NGM / 桃花源入口端末", title: "質問ペット起動画面", nameLabel: "名前", namePlaceholder: "桃花源では何と呼ばれたい？", questionLabel: "探索したい問いをひとつ入力", questionPlaceholder: "例：人をダッシュボードにしないユートピアをどう作る？", skillsLabel: "自分にはどんな技能がある？", skillsPlaceholder: "フィールドワーク、料理、コード、聞くこと、縫製、友だち召喚...", booting: "質問ペットが生まれました。3秒眺めてから入ります...", blank: "三つの欄の入力待ち", born: "ピッ！生まれた。もう逃げ出す顔をしている。", keeper: "質問ペットの飼い主", petControls: "ペット操作", choosePet: "ペットを選択", fixedPetMenu: "固定ペットメニュー" },
    dialogue: { title: "対話", askQuestion: "質問してみる", askNpc: "{name} に質問する", inputPlaceholder: "{name} - 何を聞きたい？", talkButton: "話す", closeButton: "閉じる", openWiki: "Wiki を開く", openExternalPage: "外部ページを開く", thinking: "考え中...", teachMe: "何を教えてくれる？", whereIsThis: "ここはどこ？", fallbackMission: "いま考えている任務", fallbackSkills: "自分の技能", requestFailed: "DeepSeek プロキシへのリクエストに失敗しました。" },
    archive: { tree: "アーカイブの木", title: "中央の木", description: "ここから最新情報、電子書籍、コミュニティ地図を開けます。", newsTitle: "最新情報", ebookButton: "NGM e-book", mapButton: "The Map", pdfTitle: "NGM PDF 埋め込み電子書籍", mapTitle: "NGM コミュニティ地図", communityPortals: "コミュニティ入口", embeddedLink: "埋め込みリンク", worldWiki: "World Wiki", noWikiLinks: "Wiki リンクはまだありません" },
    hud: { zoomIn: "拡大", zoomOut: "縮小", openChat: "対話を開く", openExternal: "外部リンクを開く", language: "言語", pressToTalk: "タップして話す", loadingExpedition: "派遣パネルを読み込み中...", questionPetSim: "質問ペット SIM", tick: "ティック" },
    pet: { questionPet: "質問ペット", keeper: "質問ペットの飼い主", generating: "生成中...", generationFailed: "生成に失敗しました", traits: "特徴", energy: "エネルギー", stress: "ストレス", bond: "絆", skill: "技能", originalQuestionPurpose: "元の問い / 目的", responses: "応答", shareIdeaPlaceholder: "アイデア、手がかり、応答を共有…", postResponse: "応答を送る", noResponsesYet: "まだ応答はありません", returnedNotes: "ペットが {count} 件のフィールドノートを持ち帰りました。", localOnlyNotice: "この版では派遣記録をローカルに保存します。ユーザー間同期には今後のサーバーが必要です。", smallCircleEvent: "小さな質問ペットの輪が、失敗した試みを交換し始めました。", hibernationEvent: "いくつかの質問ペットは草むらで休眠し、呼び戻されるのを待っています。", worldResonanceEvent: "桃花源が一瞬、互いに応答するネットワークになりました。", status: "状態", active: "活動中", hibernating: "休眠中", archived: "アーカイブ済み", fieldNotes: "フィールドノート", sendFieldNote: "フィールドノートを送る", fieldNotePlaceholder: "短いフィールドノートを書く...", dispatchPetOnly: "ペットだけ派遣", dispatchArchive: "派遣アーカイブ", localDispatchRecords: "ローカル派遣記録" },
    expedition: { title: "桃花源：考える生命シミュレーター派遣", templateSimulation: "テンプレート・シミュレーション", description: "あなたの任務を桃花源へ派遣し、NPC たちを記憶、推論、想像で衝突させます。", playerSummary: "派遣アバター", constraints: "制約", skills: "技能", noConstraints: "未指定", mission: "任務", maxRounds: "最大ラウンド", selectedNpcs: "選択中の NPC", run: "Mr. WHY を送る", running: "Mr. WHY が外出中...", liveLog: "ライブイベント記録", noEvents: "派遣イベントはまだありません。", round: "ラウンド", challenge: "課題", lead: "手がかり", nextQuestion: "次の問い", report: "派遣レポート", reportTitle: "桃花源 Mr. WHY 派遣レポート", originalMission: "元の任務", interpretedMission: "解釈された任務", emergentDirection: "生まれた方向性", keyEncounters: "重要な遭遇", npcDisagreements: "NPC の意見差", blindSpots: "盲点", nextActions: "具体的な次の行動", followUpQuestions: "追加の問い", researchLeads: "公募 / 研究の手がかり", downloadReport: ".md レポートをダウンロード", reportFilename: "peach-blossom-mr-why-report-ja.md" },
    encounter: { frictionCircle: "摩擦の輪", fieldTest: "フィールドテスト", nightKitchenArgument: "夜の台所での議論", archiveDetour: "アーカイブへの寄り道", prototypeOmen: "プロトタイプの兆し", abaoTitle: "Abao との遭遇", abaoHint: "Abao に近づき、リズムが問いをどう変えるか見てください。", hatchEnter: "孵化して入る" },
    api: { keyMissing: "API key がありません", keyMissingInstruction: "webview-ui/.env.local に VITE_DEEPSEEK_API_KEY を設定するか、ローカルブラウザ保存を一度行ってください。", localSettings: "ローカル API key 設定", keyLabel: "DeepSeek API key", saveLocally: "ローカルに保存", savedLocally: "ローカル保存済み", clearSavedKey: "保存済み key を削除" },
    sim: { observerMode: "キャラクターなし観察モード", stats: "統計", npcLabel: "NPC" },
    errors: { generic: "エラーが発生しました。", emptyQuestion: "先に質問を入力してください。", generationFailed: "生成に失敗しました。もう一度お試しください。" },
};
export default ja;
