import type zhTW from "./zh-TW.js";
const th: typeof zhTW = {
    common: { close: "ปิด", confirm: "ยืนยัน", cancel: "ยกเลิก", loading: "กำลังโหลด...", generate: "สร้าง", language: "ภาษา", open: "เปิด", save: "บันทึก" },
    language: { menuLabel: "ภาษา", selectLanguage: "เลือกภาษา", currentLanguage: "ภาษาปัจจุบัน: {name}" },
    home: { ngmLabel: "Non-Governmental Matters", title: "Peach Blossom Spring: ส่งเครื่องจำลองชีวิตที่คิดได้", subtitle: "มิติอุปมาแบบโต้ตอบของ Non-Governmental Matters", description: "ที่นี่คือมิติอุปมาแบบโต้ตอบ มีเพื่อนประหลาดมากมายทำดนตรีและทดลองสิ่งแปลก ๆ ร่วมกัน คุณบังเอิญพบทางเข้ามา และจะสำรวจพร้อมเก็บวิธีสร้างยูโทเปีย ลองคุยกับเพื่อนที่อาศัยอยู่ที่นี่ได้อย่างอิสระ ทุกความคิดเห็นมีสมบัติซ่อนอยู่ แต่จำไว้ว่าการกระทำของคุณมีผลต่อการเติบโตของโลกอิสระนี้ และคุณอาจพบวิธีที่ความฝันเชื่อมกับโลกจริง", createProtagonist: "สร้างตัวเอก", createTraveler: "สร้างนักเดินทางต่างโลก", playerNameLabel: "ชื่อ", playerNamePlaceholder: "ใส่ชื่อตัวละครของคุณ", roleLabel: "บทบาทปัจจุบัน", rolePlaceholder: "เช่น นักวิจัยอิสระ ศิลปิน วิศวกร ผู้เรียกเพื่อนของหมู่บ้าน", missionLabel: "ฉันต้องการอะไร", missionPlaceholder: "อธิบายความปรารถนา ความจำเป็น หรืออนาคตที่อยากให้อวตารนี้นำเข้าสู่ Peach Blossom Spring", constraintsLabel: "ข้อจำกัด (ไม่บังคับ)", constraintsPlaceholder: "เช่น ห้ามเป็นแดชบอร์ดองค์กร งบน้อย ต้องโอเพนซอร์ส ต้องมีต้นแบบในสามเดือน", avatarCollection: "วางตัวละคร", skillsLabel: "ฉันมีทักษะอะไร", skillsPlaceholder: "เช่น วิจัยภาคสนาม ฮาร์ดแวร์เปิด ภัณฑารักษ์ จัดชุมชน สิ่งทอ เขียนโปรแกรม", enterWorld: "เข้าสู่ Peach Blossom Spring", startButton: "สร้าง / เริ่ม", sendOnExpedition: "ส่ง Mr. WHY", movementHint: "เดินด้วยปุ่มลูกศรหรือ WASD บนมือถือให้ลากวงนิ้วหัวแม่มือมุมซ้ายล่าง กด Shift ค้างเพื่อเร่ง", wanderAndTalk: "เดินเล่นและพูดคุย", rotateHint: "หมุน (R)" },
    setup: { kicker: "NGM / เครื่องทางเข้า Peach", title: "หน้าจอบูตสัตว์คำถาม", nameLabel: "ชื่อ", namePlaceholder: "ให้ Peach Blossom Spring เรียกคุณว่าอะไร?", questionLabel: "ใส่คำถามหนึ่งข้อที่อยากสำรวจ", questionPlaceholder: "เช่น เราจะสร้างยูโทเปียที่ไม่เปลี่ยนผู้คนเป็นแดชบอร์ดได้อย่างไร?", skillsLabel: "ฉันมีทักษะอะไร", skillsPlaceholder: "งานภาคสนาม ทำอาหาร เขียนโค้ด ฟัง เย็บผ้า เรียกเพื่อน...", booting: "สัตว์คำถามฟักแล้ว — รอ 3 วินาทีเพื่อชมมัน...", blank: "รอให้กรอกครบสามช่อง", born: "บี๊บ! มันเกิดแล้ว และดูเหมือนพร้อมจะวิ่งหนีทันที", keeper: "ผู้ดูแลสัตว์คำถาม", petControls: "การควบคุมสัตว์คำถาม", choosePet: "เลือกสัตว์เลี้ยง", fixedPetMenu: "เมนูสัตว์เลี้ยงคงที่" },
    dialogue: { title: "บทสนทนา", askQuestion: "ถามคำถามฉัน", askNpc: "ถามคำถามกับ {name}", inputPlaceholder: "{name} - คุณอยากถามอะไร?", talkButton: "คุย", closeButton: "ปิด", openWiki: "เปิด Wiki", openExternalPage: "เปิดหน้าภายนอก", thinking: "กำลังคิด...", teachMe: "คุณสอนอะไรฉันได้บ้าง?", whereIsThis: "ที่นี่คือที่ไหน?", fallbackMission: "ภารกิจที่ฉันกำลังคิดอยู่", fallbackSkills: "ทักษะของฉัน", requestFailed: "คำขอผ่านพร็อกซี DeepSeek ล้มเหลว" },
    archive: { tree: "ต้นไม้คลังข้อมูล", title: "ต้นไม้กลาง", description: "เปิดข่าว อีบุ๊ก และแผนที่ชุมชนจากที่นี่", newsTitle: "ข่าวล่าสุด", ebookButton: "NGM e-book", mapButton: "The Map", pdfTitle: "อีบุ๊ก PDF ของ NGM แบบฝัง", mapTitle: "แผนที่ชุมชน NGM", communityPortals: "ประตูชุมชน", embeddedLink: "ลิงก์แบบฝัง", worldWiki: "World Wiki", noWikiLinks: "ยังไม่มีลิงก์ wiki" },
    hud: { zoomIn: "ขยาย", zoomOut: "ย่อ", openChat: "เปิดบทสนทนา", openExternal: "เปิดลิงก์ภายนอก", language: "ภาษา", pressToTalk: "แตะเพื่อคุย", loadingExpedition: "กำลังโหลดแผงการเดินทาง...", questionPetSim: "ซิมสัตว์คำถาม", tick: "จังหวะ" },
    pet: { questionPet: "สัตว์คำถาม", keeper: "ผู้ดูแลสัตว์คำถาม", generating: "กำลังสร้าง...", generationFailed: "สร้างไม่สำเร็จ", traits: "ลักษณะ", energy: "พลังงาน", stress: "ความเครียด", bond: "สายสัมพันธ์", skill: "ทักษะ", originalQuestionPurpose: "คำถาม / เป้าหมายเดิม", responses: "คำตอบ", shareIdeaPlaceholder: "แบ่งปันไอเดีย เบาะแส หรือคำตอบ…", postResponse: "ส่งคำตอบ", noResponsesYet: "ยังไม่มีคำตอบ", returnedNotes: "สัตว์คำถามของคุณกลับมาพร้อมบันทึกภาคสนาม {count} รายการ", localOnlyNotice: "เวอร์ชันนี้เก็บบันทึกการส่งไว้ในเครื่อง หากต้องซิงก์ข้ามผู้ใช้ ต้องมีเซิร์ฟเวอร์ในอนาคต", smallCircleEvent: "วงเล็ก ๆ ของสัตว์คำถามเริ่มแลกเปลี่ยนความพยายามที่ล้มเหลวกัน", hibernationEvent: "สัตว์คำถามบางตัวมุดเข้าไปจำศีลในหญ้า รอให้ถูกเรียกกลับ", worldResonanceEvent: "Peach Blossom Spring กลายเป็นเครือข่ายที่ตอบกันเองชั่วครู่", status: "สถานะ", active: "ทำงานอยู่", hibernating: "จำศีล", archived: "เก็บแล้ว", fieldNotes: "บันทึกภาคสนาม", sendFieldNote: "ส่งบันทึกภาคสนาม", fieldNotePlaceholder: "เขียนบันทึกภาคสนามสั้น ๆ...", dispatchPetOnly: "ส่งเฉพาะสัตว์คำถาม", dispatchArchive: "คลังการส่ง", localDispatchRecords: "บันทึกการส่งในเครื่อง" },
    expedition: { title: "Peach Blossom Spring: ส่งเครื่องจำลองชีวิตที่คิดได้", templateSimulation: "การจำลองจากแม่แบบ", description: "ส่งภารกิจของคุณเข้า Peach Blossom Spring แล้วให้ NPC ปะทะกันผ่านความทรงจำ การคาดคะเน และการจินตนาการ", playerSummary: "อวตารการเดินทาง", constraints: "ข้อจำกัด", skills: "ทักษะ", noConstraints: "ยังไม่ได้ระบุ", mission: "ภารกิจ", maxRounds: "จำนวนรอบสูงสุด", selectedNpcs: "NPC ที่เลือก", run: "ส่ง Mr. WHY", running: "Mr. WHY ออกเดินทางอยู่...", liveLog: "บันทึกเหตุการณ์สด", noEvents: "ยังไม่มีเหตุการณ์การเดินทาง", round: "รอบ", challenge: "ความท้าทาย", lead: "เบาะแส", nextQuestion: "คำถามถัดไป", report: "รายงานการเดินทาง", reportTitle: "รายงาน Mr. WHY ของ Peach Blossom Spring", originalMission: "ภารกิจเดิม", interpretedMission: "ภารกิจที่ตีความแล้ว", emergentDirection: "ทิศทางที่เกิดขึ้น", keyEncounters: "การพบเจอสำคัญ", npcDisagreements: "ความเห็นต่างของ NPC", blindSpots: "จุดบอด", nextActions: "ขั้นตอนถัดไปที่ชัดเจน", followUpQuestions: "คำถามต่อเนื่อง", researchLeads: "ประกาศรับสมัคร / เบาะแสวิจัย", downloadReport: "ดาวน์โหลดรายงาน .md", reportFilename: "peach-blossom-mr-why-report-th.md" },
    encounter: { frictionCircle: "วงแรงเสียดทาน", fieldTest: "ทดสอบภาคสนาม", nightKitchenArgument: "การโต้เถียงในครัวกลางคืน", archiveDetour: "ทางอ้อมสู่คลังข้อมูล", prototypeOmen: "ลางของต้นแบบ", abaoTitle: "การพบกับ Abao", abaoHint: "เข้าใกล้ Abao แล้วดูว่าจังหวะเปลี่ยนคำถามอย่างไร", hatchEnter: "ฟักและเข้าไป" },
    api: { keyMissing: "ไม่มี API key", keyMissingInstruction: "ตั้งค่า VITE_DEEPSEEK_API_KEY ใน webview-ui/.env.local หรือบันทึกไว้ในเบราว์เซอร์เครื่องนี้หนึ่งครั้ง", localSettings: "ตั้งค่า API key ในเครื่อง", keyLabel: "DeepSeek API key", saveLocally: "บันทึกในเครื่อง", savedLocally: "บันทึกในเครื่องแล้ว", clearSavedKey: "ลบ key ที่บันทึกไว้" },
    sim: { observerMode: "โหมดสังเกตการณ์ไม่มีตัวละคร", stats: "สถิติ", npcLabel: "NPC" },
    errors: { generic: "เกิดข้อผิดพลาด", emptyQuestion: "กรุณาใส่คำถามก่อน", generationFailed: "สร้างไม่สำเร็จ กรุณาลองอีกครั้ง" },
};
export default th;
